# Generated by Django 5.2.8 on 2025-11-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('En preparación', 'En preparación'), ('Listo para entregar', 'Listo para entregar'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado')], default='En preparación', max_length=50),
        ),
    ]
