# Generated by Django 5.2.7 on 2025-11-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_alter_pedido_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='personalizacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
