# Generated by Django 5.2.7 on 2025-11-17 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_insumo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='insumos',
            field=models.ManyToManyField(blank=True, related_name='productos', to='productos.insumo'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
