# Generated by Django 5.2.7 on 2025-11-17 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_producto_insumos_alter_insumo_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
