# Generated by Django 5.2.7 on 2025-12-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_insumo_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='es_extra',
            field=models.BooleanField(default=False, verbose_name='¿Es extra?'),
        ),
    ]
